spring:
  application:
    name: reportingservice
server:
  port: 8080

---
spring:
  profiles: dev
  application:
    name: reportingservice
server:
  port: 9090

---
spring:
  profiles: prod
  application:
    name: reportingservice
server:
  port: 4431